### ISSUE TITLE
Make flex take floats instead of strings

### ISSUE THREAD

**Issue by TheSeamau5** [TheSeamau5/flex-html#6]
@GlenDC I'm giving you the heads-up on this change. I looked through the [w3c spec](http://www.w3.org/TR/css-flexbox-1/#propdef-flex-grow) and it turns out that there are no funky values and I can just pass floats to stuff like "flex-grow"

This means that we'll get the following types for functions:

``` elm
grow : Float -> List (String, String)
shrink : Float -> List (String, String)
basis : Float -> List (String, String)
flex : Float -> Float -> Float -> List (String, String)
```

**Comment by TheSeamau5** [comment]
Hmm, looks like "flex-basis" can take some "content"...http://www.w3.org/TR/css-flexbox-1/#propdef-flex-basis

**Comment by GlenDC** [comment]
Nice :) Stuff like basis could do well with a tiny library that makes all these funky values easy. Kinda like what they tried with elm-types-styles, but complete.
